[gcp_service_account]
type = "service_account"
project_id = "tvoj-projekt-id"
private_key_id = "tvoj-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nOVDJE_UNESI_SVOJ_KLJUČ\n-----END PRIVATE KEY-----\n"
client_email = "tvoj-service-account@tvoj-projekt-id.iam.gserviceaccount.com"
client_id = "tvoj-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tvoj-service-account%40tvoj-projekt-id.iam.gserviceaccount.com"

sheet_url = "https://docs.google.com/spreadsheets/d/1u1CPEMq8yrUjnQ5FOncQKVUndzk9ljlEPZ6IyFrhRH4/edit#gid=0"
